import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  map,
  rules
}: Readonly<{
  children: React.ReactNode;
  map: React.ReactNode;
  rules: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {map} */}
        {/* {rules} */}
        {children}
        </body>
    </html>
  );
}
